### ISSUE TITLE
Security concerns about storing the GitHub token

### ISSUE THREAD

**Issue by orhun** [oz/gist#3]
Hello!

I have a few concerns about storing the GitHub token for using `gist`. It is said in README.md that `GITHUB_GIST_TOKEN` or `GITHUB_TOKEN` can be placed into `.profile` or some other location that the shell uses to store environment settings. However, the problem with that approach is that, it makes the variable globally accessible across the shell sessions. That's why I think storing **any** token in a shell profile is not secure enough. Do you have any other recommendations/tricks regarding this?

Also, it would be much better if there was a global configuration file that `gist` supports for storing these type of variables. So that this file can be placed into a global location where `gist` looks for as default, e.g. `~/.gist/config` or `~/.gist/credentials` (very much like `~/.cargo/credentials`)

I'm not sure if my suggestions were overly complex for a simple program like `gist`, but "compromising the simplicity" can be negligible when it comes to security 🙂 

Tell me what you think 🐻

**Comment by oz** [comment]
Hi there!

I understand the risk you're pointing out: environment variables are not the best place to store super sensitive information. To mitigate that discomfort, you could generate a gist token that only allows access to the Github Gist API.

All in all, I don't think that having a (clear text?) configuration file would greatly improve the operational security, but while it is not part of _my_ threat model I will gladly consider contributions that provide the feature. It would be nice to fall back to env. vars if no configuration file is found.

If you're more paranoid, you could also consider:

- [magit's approach with pgp](https://magit.vc/manual/ghub/Storing-a-Token.html) (but now you're forking to decrypt a token to post a gist... 🤔)
- using the system's keyring 🤷🏻.

**Comment by orhun** [comment]
Thank you for the recommendations! Generating a token that only allows gist access definitely makes sense. On top of that, I decided to go with a different approach this time so I used `keyctl` as following:

```sh
$ keyctl add user gist_token <ghp_token> @u

$ keyctl print $(keyctl request user gist_token)
<ghp_token>
```

And, in my `.bashrc`:

```sh
export GITHUB_GIST_TOKEN=$(keyctl print $(keyctl request user gist_token))
```

**EDIT**: Looks like the user keyring is not persistent as default. I will try something else 🙂 

> All in all, I don't think that having a (clear text?) configuration file would greatly improve the operational security, but while it is not part of _my_ threat model I will gladly consider contributions that provide the feature. It would be nice to fall back to env. vars if no configuration file is found.

I'd be happy to implement this. Just let me know if/when you consider doing it and I can start working on a PR.

**Comment by oz** [comment]
@orhun The `keyctl` thing looks nicer. 👍🏻 

If you'd like to work on a configuration file thing, then do by all means. I'd be happy to get more eyes on the current code, and that particular feature seems to scratch your own itch. 😄

I'd eventually get to it as day-work calms down, but that's not going to happen in 2021 for me. 😓

**Comment by orhun** [comment]
I found another solution instead of having a global configuration file, using [pass](https://www.passwordstore.org/):

```sh
pass insert github/gist_token
```

```sh
gist() {
    GITHUB_GIST_TOKEN=$(pass github/gist_token) "$HOME/.cargo/bin/gist"
}
```

However, I'm going to submit a PR about the configuration file soon.

**Comment by oz** [comment]
Thank you, merged!
